### ISSUE TITLE
Is this project still being actively supported?

### ISSUE THREAD

**Issue by sceptre12** [nmccready/cesium-navigation#4]
The current version of Cesium is 1.59, however this project still has a dependency on 1.48 @nmccready

**Comment by nmccready** [comment]
I'm not checking cesium daily for updates but PRS to keep this library in sync are welcomed.

**Comment by nmccready** [comment]
It would be nice if some integration or unit tests exist which provided more of a sanity check prior to publishing. 
I guess running the examples will have to suffice for now.

**Comment by nmccready** [comment]
> 1.59, however this project still has a dependency on 1.48

To be accurate this is a loose dependency on  **caret** `^1.48`. In theory if Cesium doesn't break semantic versioning then this library is not out of date until they go to version 2.x. So I think this can be closed unless you can confirm this is no longer working.

**Comment by sceptre12** [comment]
Thank you, I'll let you know if I run into any issues
