### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defined' of undefined

### ISSUE THREAD

**Issue by ghost** [nmccready/cesium-navigation#7]
I'm getting `Uncaught TypeError: Cannot read property 'defined' of undefined` from the esm.js file. It seems to be an issue with how Cesium is being imported. It works if I use

`import { SvgPathBindingHandler, getElement, defined, DeveloperError, EllipsoidGeodesic, Cartesian2, getTimestamp, EventHelper, defineProperties, Camera, Rectangle, Cartographic, Ray, Cartesian3, SceneMode, IntersectionTests, Math as Math$1, Transforms, Matrix4, BoundingSphere, HeadingPitchRange, Event } from 'cesium';`

**Comment by easternmotors** [comment]
This is due to you being on a Cesium version > 1.62. I am going to put in a PR for this because I need the support as well. In case you weren't aware: https://cesium.com/blog/2019/10/31/cesiumjs-es6/

**Comment by easternmotors** [comment]
@nmccready https://github.com/nmccready/cesium-navigation/pull/8/

**Comment by nmccready** [comment]
landed 17b4cc22f28e2134cec3e4272c280a606217803f
